### ISSUE TITLE
Doesn't work (at last with Shabegom Paste that shizz)

### ISSUE THREAD

**Issue by Mara-Li** [TfTHacker/obsidian42-brat#1]
![image](https://user-images.githubusercontent.com/30244939/135769693-6c2e3e87-dee0-4a86-bb2c-c7ecd8b5c66f.png)
Link to github : https://github.com/shabegom/paste-that-shizz

**Comment by TfTHacker** [comment]
Hi. Try it with just this: 

shabegom/paste-that-shizz

**Comment by Mara-Li** [comment]
Okay! I understand now ^^' sorry for the issue! It's a great plug-in and I don't encounter other problem.
It can be cool to add this in the Readme!

**Comment by TfTHacker** [comment]
ok. will do something about that in the help.

also will add some smartness of how adding repositories are handled. seems like what you did would be a common use scenario.

**Comment by TfTHacker** [comment]
Most recent update in releases handles this. https://github.com/TfTHacker/obsidian42-brat/releases/tag/0.12

Also you can “add” this plugin to brat to make it self-updating :-)
