### ISSUE TITLE
Automatic updating not working anymore

### ISSUE THREAD

**Issue by DutchPete** [TfTHacker/obsidian42-brat#11]
I have this feature enabled, and it was working, but the last couple of days it is not working anymore. Anything going on with the plug-in?
Please advise.

**Comment by TfTHacker** [comment]
I just tested and this is working. It waits a good minute or before the autupdate happens in background. I will shorten this.

Does a manual check for updates work?

**Comment by TfTHacker** [comment]
P.S. I am going to be adding logging support, so you can see what plugin is doing behind the scenes.

**Comment by DutchPete** [comment]
Yes, maual check for updates works.

**Comment by TfTHacker** [comment]
I just updated brat. It now runs the update check about 10 seconds after startup. Also it does a console log so you can see the process started or stopped.

See if this is working for you. Tnx

**Comment by DutchPete** [comment]
This is what I see in the Console:

<img width="227" alt="console" src="https://user-images.githubusercontent.com/10794265/140272824-4f31c5c0-7715-4108-886d-cd71c7de6049.png">

What does that tell me? Sorry for a basic question.

**Comment by TfTHacker** [comment]
No worries. You see the line BRAT started and finished check. this tells you that it ran.

updates will  appear as blue notifications. but basically the start/finish runs silently in the background on startup unless there is something to update.

**Comment by DutchPete** [comment]
OK, clear. Let's see if the blue notifications appear when BRAT has a plug-in to update.

**Comment by TfTHacker** [comment]
one thing you can do if you are so technically incllined is to go into your plugins folder and open a manifest.json file for a plugin registered with BRAT and change the "version" number. for example if it say "0.5.0" you can change it to "0.5.1" and BRAT will see it as different and should then on startup redownload the plugin (since versions don't match).

no need to do this unless you want to test it through without waiting.

**Comment by DutchPete** [comment]
For 1 of the plug-ins I changed a version from 0.4.2 to 0.4.3. Waited at least ½ a minute, nothing happened. Then I refreshed Obs, and some 10 secs later the notification popped up. When I looked in the manifest.json file BRAT had changed the version back to 0.4.2.

So I guess it works now.

**Comment by TfTHacker** [comment]
Great! that is the desired behavior. Autoupdate works only on startup and it is set to go off about 10 seconds after obsidian has fully  loaded.

Thank you for working through this with me.

**Comment by DutchPete** [comment]
I did not know autoupdate only works on start-up. Now I know, and that's good.
Thanks for the plug-in. 👍
