### ISSUE TITLE
A few questions about how this plugin works

### ISSUE THREAD

**Issue by Taitava** [TfTHacker/obsidian42-brat#12]
Hi,

I'd like to ask about how this plugin works. I read the README.md file, but I still have a few questions in mind:
 - If a plugin does not have a `manifest-beta.json` file, how does BRAT differ from just installing the same plugin via the normal community plugin installation process? Does it allow installing plugins that are not yet available in the community plugins list? Any other differences?
 - If my plugin has `manifest-beta.json`, can I mark the beta release in GitHub as a _pre-release_?
 - Can beta version use aplhanumeric characters in the version name? E.g. if I'm developing version `2.1.0`, I might want to release a beta version named `2.1.0-beta1` so that beta testers can easily distinguish later if they have are still using a beta version, or if they have already upgraded to the "real", stable `2.1.0` version.

Thanks! 🙂 

P.S. Have you considered opening a Discussions section for this kind of topics?

**Comment by TfTHacker** [comment]
Your questions and feedback are always warmly welcomed.

If manifest-beta.json doesn’t exist, BRAT will use manifest.json, and this is true for plugins in community list or not in the community list. This is useful for when you have not yet shipped the plugin. However, after shipping the plugin to the community, then manifest-beta.json allows you to have a “beta channel”. Brat will always use the manifest-beta.json if it exists.  In this case it is even possible that BRAT could be behind the community release if you update manifest.json to a newer release, but don’t update manifest.


Simply put: if manifest-beta.json exists, it is always always always used. If it doesn’t exist, it falls back to manifest.json

Yes you can mark as pre-release when using manifest.json or manifest-beta.json.

The version number is actually not important. Obsidian just looks at the version you have installed and compares it to the version in manifest.json on the root of your repository, if they don’t match, obsidian downloads the release based on the manifest.json. BRAT works in the same way. 

Simply put, the version number is for humans, Obisidan just uses whatever manifest.json says in the root of the repository and BRAT follows this.

I will turn discussions on. Thank you!

**Comment by Taitava** [comment]
Thank you! 🙂
