### ISSUE TITLE
BRAT does not update

### ISSUE THREAD

**Issue by DutchPete** [TfTHacker/obsidian42-brat#17]
I have version 0.5.6 installed. When I go to Obsidian settings and click on “Check for updates” it does not find 0.5.7. I thought BRAT could update itself too.

**Comment by TfTHacker** [comment]
For BRAT to update itself, it has to be added to the list of beta plugins. So please add this repository to brat, then update should work.

**Comment by DutchPete** [comment]
Wow, that's a quick reply. Yes, it works now, thanks a lot.
Might be an idea to add your comment to the README.

**Comment by TfTHacker** [comment]
I was thinking of adding a toggle to make BRAT self-updating.

**Comment by DutchPete** [comment]
Even better.
