### ISSUE TITLE
command “Grab a beta theme for testing from a Github repository”: missing

### ISSUE THREAD

**Issue by DutchPete** [TfTHacker/obsidian42-brat#18]
I am now on 0.5.7 and want to install an beta theme, but the command **Grab a beta theme for testing from a Github repository** is not in the palette list.

**Comment by TfTHacker** [comment]
Please try a restart to Obsidian.

Also is the command available from the BRAT ribbon button?

**Comment by DutchPete** [comment]
OK, that's fine now, many thanks. I don't use the ribbon, I prefer keyboard shortcuts 😀
