### ISSUE TITLE
Notifications stay too long

### ISSUE THREAD

**Issue by chrisgrieser** [TfTHacker/obsidian42-brat#2]
I'd love to follow the instruction, but the notifications are big, stay for a long time, and are literally blocking the button I need to press ;)

Nevertheless, great idea to do this plugin, thanks a lot for it. 

<img width=50% alt="Screenshot 2021-10-03 23 46 32" src="https://user-images.githubusercontent.com/73286100/135772578-2078e2d0-af98-4894-a50d-ed59bc81b33d.png">

**Comment by TfTHacker** [comment]
You can click on the bubble and it will disappear.

The issue is making sure the user knows there has been some kind of change. Let me know if you think the time should be shorter.

By the way you can add BRAT to beta plugin list so BRAT self-updates :-)
