### ISSUE TITLE
Could "Switch active theme" have a "Default" option

### ISSUE THREAD

**Issue by claremacrae** [TfTHacker/obsidian42-brat#20]
Thank you for this amazing plugin.

I love "Switch active theme" and have it on my ribbon.

As far as I can see, to turn off all themes I need to go to the main Appearance settings, select Themes > Manage and select Default/Obsidian...

Might it be possible for BRAT to streamline that? Adding it an an extra option to "Switch active theme" sounds to me like a good place, but I don't know the technicalities involved...

**Comment by dkapila** [comment]
+ 1 for this :) Would it be possible to add an option to switch to the default theme?
 
For plugin development, I like to switch every now and then to Default, to ensure it works well on the vanilla theme as well.

**Comment by TfTHacker** [comment]
Just added this with last update.

https://github.com/TfTHacker/obsidian42-brat/releases/tag/0.6.1

**Comment by claremacrae** [comment]
Awesome - huge thanks, this is a real timesaver :-)
