### ISSUE TITLE
[FR] Disable request if no internet

### ISSUE THREAD

**Issue by Mara-Li** [TfTHacker/obsidian42-brat#23]
Sometimes, I use Obsidian without internet, and, when started without, there is a lot of notification with error about manifest not found.
It's very inconvenient, mainly on phone-tablette.

So, it will be good to disable request in these case.

**Comment by TfTHacker** [comment]
This is addressed with 0.6.2 release (now in beta testing with BRAT :-) 

Though with one caveat, I only check where there are bulk activities, such as checking for all plugins or themes.  I left them as they are for individual commands (which aren't so intrusive).

Thank you for reporting this.
