### ISSUE TITLE
Option to delay checking for updates

### ISSUE THREAD

**Issue by ankushg** [TfTHacker/obsidian42-brat#27]
Obsidian can sometimes take a while to startup if I have too many plugins installed and they're all trying to do work in the background at launch.

It would be nice if I could delay BRAT's update checker by an arbitrary amount of time (e.g., 5 min after obsidian has launched)

**Comment by TfTHacker** [comment]
This is addressed with 0.6.2 release (now in beta testing with BRAT :-)

I made the delay to be 1 minute for plugins, 2 minutes for themes.
