### ISSUE TITLE
is it possible to install a specific version of the plugins?

### ISSUE THREAD

**Issue by fyears** [TfTHacker/obsidian42-brat#30]
Sometimes we may want to install a previous, or a specific version of the plugins. Is it possible to do so in BART? Obsidian obviously would not support this.

Maybe BART can support some syntax like `user/repo#1.0.0`?

Thanks!

**Comment by TfTHacker** [comment]
Technically it would be possible. All the plumbing is in BRAT for it, but it would be a separate feature. For now I will keep it on the “possible” list. PR’s always welcome :-)

**Comment by fyears** [comment]
Hi I made a pr. Would you like to check if the code is ok? Thanks!

**Comment by TfTHacker** [comment]
This is really awesome. I declined the PR for a few reasons, please look. I hope you will resubmit based on my feedback.

**Comment by TfTHacker** [comment]
By the way, do you have a twitter or discord account (for Obsidian) so I can give you credit once this feature is announced?

**Comment by fyears** [comment]
Thanks. It's my honor to contribute to the obsidian community. My discord account is `fyears#3888`.

**Comment by TfTHacker** [comment]
this is now pushed out the public. thank you again @fyears for your help.
