### ISSUE TITLE
[Feature Request] Gitlab

### ISSUE THREAD

**Issue by yorrd** [TfTHacker/obsidian42-brat#31]
Hi man, thanks for this. 

I'm wondering, BRAT seems to be biased on GitHub atm. Do you have plans to allow publicly hosted repos from gitlab (maybe even self-hosted gitlabs) as well? The use case is that my company wants us to keep everything orderly on our gitlab. We're still going to open source it at some point and then probably move to GitHub, but for the moment, I'd love to test on gitlab. 

Wdyt?

**Comment by TfTHacker** [comment]
Thank you for writing. At this point as far as I can tell, the community plugin system only works from GitHub. It won't pull from other sources.

of course plugins can be manually installed from any source.

BRAT is really aimed at working with the native features of Obsidian. So your idea is good, but would require building support for something far from the mainstream.

Having said that, pull requests are always welcome.
