### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by menagerie198** [TfTHacker/obsidian42-brat#34]
the latest version is not installing in my Obs. I uninstalled, and tried re-installing... now I have no BRAT = sad

**Comment by brimwats** [comment]
Same

**Comment by ChurchillDu** [comment]
It says" Plugin ID mismatch" when installing.

**Comment by TfTHacker** [comment]
@menagerie198 @brimwats @ChurchillDu  please try updating now and let me know how it goes.

**Comment by ChurchillDu** [comment]
> @menagerie198 @brimwats @ChurchillDu please try updating now and let me know how it goes.

I have successfully installed. Good job!👍

**Comment by menagerie198** [comment]
Successfully installed = happy! Cheers
