### ISSUE TITLE
[Feature request] Specify branch for beta

### ISSUE THREAD

**Issue by Snezhig** [TfTHacker/obsidian42-brat#35]
Nice plugin, thanks.
I would like to have a possibility to specify a branch for beta releases.
As I understand I have to have actual manifest-beta.json in branch for releases and I have to chose between two options:
1. Merge beta code with new version with master
2. Create separate commit to update manifest-beta.json and resolve conflicts lately.

But it will be great to have a file, for example, manifest-beta-brach.json where I can specify branch which have actual manifest-beta.json.

**Comment by TfTHacker** [comment]
Actually, the manifest-beta.json just points to a "Release". So if you can generate a release from a specific branch and point the manifest-beta.json to that release, BRAT will pull that release.

There is a "Frozen" version option where a user can also specify a release number and its a one time install. See step 3 here for frozen version: https://github.com/TfTHacker/obsidian42-brat#adding-a-beta-plugin

**Comment by TfTHacker** [comment]
This is a great idea, but its beyond the scope for now. Frankly I just don't have the time to take it much deeper. Sorry.
