### ISSUE TITLE
Unable to install latest version of plugin

### ISSUE THREAD

**Issue by AB1908** [TfTHacker/obsidian42-brat#37]
Hello TfTHacker! Been a while haha.

I've been trying to install the latest release of my SRS plugin fork but it errors out. It works if I try to install a specific version with the correct version name though.

Release for reference: https://github.com/AB1908/obsidian-spaced-repetition/releases/tag/1.7.3-c

Any idea where the problem might be?

**Comment by TfTHacker** [comment]
The manifest.json file on the root folder of the repo points to 1.7.3. If you want 1.7.3-c to be used, it needs to be changed in that file.

However, if you are in "beta testing mode", create a manifest-beta.json file and add that to the root. It should have all the same info, except the version should be 1.7.3-c.

BRAT ignores manifest.json if there is a manifest-beta.json file. If there is no manifest-beta.json file, it uses the default manifest.json.

There are some more details about this documented here:
https://github.com/TfTHacker/obsidian42-brat/blob/main/help/developers.md

I wish you success on your fork, this is a good plugin.
