### ISSUE TITLE
Respect minAppVersion when installing/updating plugins

### ISSUE THREAD

**Issue by nothingislost** [TfTHacker/obsidian42-brat#38]
It would be helpful if BRAT could respect the `minAppVersion` from `manifest.json` to avoid installing or updating any plugins that are incompatible with the user's current Obsidian version. There's a number of breaking changes in Obsidian 0.15.x and it's difficult to beta test them via BRAT since non 0.15.x users will get the updates via BRAT even though the `minAppVersion` is set.

One step further would be to also respect versions.json which lets you know which version of the plugin you should step down to in the case of an incompatibility.

**Comment by TfTHacker** [comment]
Sorry for delay in response. I am looking into this now and agree this would be a good fix.

i am not familiar with versions.json. where can I get more info on that?

**Comment by TfTHacker** [comment]
This is now resolved with 0.6.35 update to BRAT.
