### ISSUE TITLE
Logging location?

### ISSUE THREAD

**Issue by chrisweis** [TfTHacker/obsidian42-brat#39]
It would be helpful if this Logging page had a bit more detail about the location of the logs (I was hunting in the underlying plugin folder not realizing it logs to the vault notes):
https://github.com/TfTHacker/obsidian42-brat/blob/main/help/logging.md

Great plugin!  Thanks

**Comment by TfTHacker** [comment]
Nice to hear from you. I will update the text with this recommendation. thank you.
