### ISSUE TITLE
Beta plugin updates do not complete

### ISSUE THREAD

**Issue by argenos** [TfTHacker/obsidian42-brat#40]
Seems there is a bug when reading the manifest of some manually installed plugins: 
![image](https://user-images.githubusercontent.com/5426039/183389952-7b84d88b-3ee2-4c8e-b963-c5590fcf96fa.png)

**Comment by TfTHacker** [comment]
Can you provide me with more details? Do you mean a plugin installed by the user directly?

**Comment by TfTHacker** [comment]
This is now resolved with 0.6.35 update to BRAT.
