### ISSUE TITLE
Theme downloads are not tracked

### ISSUE THREAD

**Issue by Fevol** [TfTHacker/obsidian42-brat#41]
When a theme is normally downloaded via Obsidian's theme browsers, the download is tracked by sending a request to `https://releases.obsidian.md/stats/theme/THEME-NAME/download`. 

Not sure how many people actually download themes via this plugin, but this ensures that those downloads are being tracked too!

**Comment by TfTHacker** [comment]
Thanks for reaching out. BRAT is designed as a testing tool. The assumption is only testers would use BRAT for instal and testing. Eventually when theme or plugin finish their testing, users would disconnect BRAT and just use the available solution from within Obsidian's community plugin or themes tools.

Some may use BRAT though for installing themes and plugins, and it works, but its beyond the scope of this tool.  Hence the BR in BRAT "Beta Reviewer's".
