### ISSUE TITLE
Uninstalled plugins not offloading from data.json

### ISSUE THREAD

**Issue by pcuellar** [TfTHacker/obsidian42-brat#43]
After uninstalling plugins loaded with BRAT, I am finding they get loaded again upon triggering the "Check for updates to all beta plugins and UPDATE" command. After looking at the `data.json` file, I can confirm that after being uninstalled, plugins remain listed in the file. 

I am using Obsidian v0.16.2, installer version: v0.15.9. BRAT version: 0.6.35.

**Comment by TfTHacker** [comment]
Thank you for reaching out. Just to double-check. When removing a BRAT installed plugin, you need to do two things:

1) Delete it from community plugins as you normally would with all plugins (this actually deletes it from disk)
2) In Settings > BRAT remove the beta plugin from the list of plugins monitors

Basically these two areas work independently of one another. Example: It could be you want the beta plugin to stay installed, but don't want BRAT to update it. In this case you would remove it from BRAT, but leave it in settings.

Little more work for you, but you have more control.

If this wasn't the problem, let me know.

**Comment by pcuellar** [comment]
Hey @TfTHacker. I followed your instructions and noticed that the settings on BRAT don't show any plugin listed, even though the plugins are in the data.json file, they show as installed and I can normally use them. See the screenshots below:

<img width="817" alt="Screen Shot 2022-09-06 at 10 02 51 PM" src="https://user-images.githubusercontent.com/20482146/188772624-7b6ea120-e98d-4e20-aec4-7be1628bea05.png">
<img width="835" alt="Screen Shot 2022-09-06 at 10 02 31 PM" src="https://user-images.githubusercontent.com/20482146/188772637-f6304fcf-ed51-4a1e-8542-f341ef58563a.png">
<img width="282" alt="Screen Shot 2022-09-06 at 10 02 13 PM" src="https://user-images.githubusercontent.com/20482146/188772657-56505724-616e-4188-971c-d1e591c698dc.png">

**Comment by TfTHacker** [comment]
Hmmm, odd for sure. There is nothing wrong with you deleting the data.json file and having it reinitialized by BRAT.
