### ISSUE TITLE
Feature Request: Savestate Plugin-Enabled-State, then mass-disable all plugins

### ISSUE THREAD

**Issue by Gewerd-Strauss** [TfTHacker/obsidian42-brat#44]
Hello,

this plugin can be really useful, especially when you have 64 active plugins and 7 inactive installed. (Never noticed it was _that_ many).

Sometimes you encounter bugs that you are unsure where it comes from, and after checking that the sandbox vault doesn't replicate the issue then fun experience of "Let's find the responsible plugin" commences. I would like to propose an additional feature for such instances:

I would like to be able to:
1. disable all currently active plugins
2. then enable a set of plugins to narrow down my issue // do whatever testing I need in separation, and then
3. reset to the state of all plugins before disabling. This means deactivating all plugins which are now active and have not been active before as well as activating all plugins which were active before and are no longer active when the command is executed.

I suppose this principle could be expanded to save plugin-specific settings-snapshots when executing this command, so that the settings of those plugins are preseved as well (in case you need to test any larger set of changes)

Would something like this be possible? 

Thank you,
Sincerely 
~Gw

**Comment by TfTHacker** [comment]
There is a plugin in the store that solves this problem, so I won't be adding it to BRAT. Thank you for the excellent suggestion.
