### ISSUE TITLE
Recommended way to include an additional file in a plugin

### ISSUE THREAD

**Issue by benr77** [TfTHacker/obsidian42-brat#46]
I maintain a plugin called [Obsidian Gitlab Issues](https://github.com/benr77/obsidian-gitlab-issues). It needs to provide a default Handlebars.js template, which currently is an additional file in the repository.

What is the recommended way of getting this file installed alongside the plugin files?

From what I've read, only the mainfest, JS and CSS files are installed by default.

Thanks

**Comment by TfTHacker** [comment]
Hi Ben, I am glad to hear from you. When I developed BRAT, at that time I learned that Obsidian only downloads three files from the published package on your repo: 
- manifest.json
- main.js
- styles.css

all other files are ignored. I don' think that changed. (Correct me if I am wrong).

What you want to do is include your dependency on handlebars so it gets built into your main.js.

You can see for example in another plugin I developed the include of a third party library:
https://github.com/TfTHacker/obsidian42-strange-new-worlds/blob/44fb0d9f9cfd8ca01369e99ac137f32d2b9679aa/package.json#L27

Hope this helps.

**Comment by benr77** [comment]
Thanks for your response. I think you are correct and that these three files are the only ones to be downloaded.

However, I was actually talking about a Handlebars template file, not the Handlebars library itself. The library is in my `package.json` but gets compiled in to the outputted `main.js` so that's fine. But I want to ship an example, default template file that can be used if the user does not define their own.

I'm wondering if I should just include this template directly in the source code, so it ends up in `main.js` instead of trying to read it from disk. I guess the other option would be to write it to disk on plugin load (if it does not already exist).

Any thoughts on this?

Thanks

**Comment by TfTHacker** [comment]
Oh, sorry! I misunderstood. Obsidian won't download other files, so you need to figure out how to include that in another way. I would include the template in your code. 

I wish you success in your dev efforts!
