### ISSUE TITLE
BRAT Not grabbing latest version

### ISSUE THREAD

**Issue by erohtar** [TfTHacker/obsidian42-brat#49]
For the ['DB Folder' plugin](https://github.com/RafaelGB/obsidian-db-folder), the latest release is v3.1.2, but BRAT insists on getting v3.0.1 for some reason. What's the fix?
Thank you

**Comment by TfTHacker** [comment]
The developer of this plugin has a manifest-beta.json that tells BRAT which version is for testing. They need to either update this manifest file or remove it and BRAT will fall back to the manifest.json of the repository. I would suggest you report this to the developer.

If you remove the plugin from BRAT, then obsidian can update the plugin directly.
