### ISSUE TITLE
Command palette option for forcing installation/reinstallation of plugins added to BRAT

### ISSUE THREAD

**Issue by frigvid** [TfTHacker/obsidian42-brat#50]
Currently, I have a configuration file I was testing locked version plugins with, however I noticed that it would not install them always. Adding them through the GUI does work, of course, but subsequent changes are not detected. For example, removing a plugin manually makes it essentially impossible for it to be automatically reinstalled, likewise does deleting it from the GUI but leaving it within BRAT. Adding entries directly to `data.json` for BRAT are also not detected. None of these change between Obsidian restarts or simple reloads of Obsidian from the command palette.

An automatic detection for their state is perhaps a tad out of scope, but I think an option that installs/reinstalls all plugins listed in `data.json` would be very welcome.

**Comment by TfTHacker** [comment]
So basically just to force the download of the plugin again? I am sorry I didn't fully follow the request.

**Comment by frigvid** [comment]
In the sense that it should check if the plugin that is listed in BRAT is installed or not and install it when it detects it isn't installed, and to check if new entries to `data.json` are added and install them. Likewise, it should keep track of or be able to check if a plugin has been deleted manually or not, because currently, doing so will leave it essentially impossible to be automatically reinstalled through BRAT.

**Comment by TfTHacker** [comment]
I believe this is new "reinstall" feature can address this request. Maybe not 100%, but probably good enough.

https://github.com/TfTHacker/obsidian42-brat/releases/tag/0.7.1
