### ISSUE TITLE
"main.js not found in the Release"

### ISSUE THREAD

**Issue by caseywatts** [TfTHacker/obsidian42-brat#51]
Hi!

When I try to add [my beta plugin obsidian-compromise](https://github.com/caseywatts/obsidian-compromise/) via BRAT, I get this message:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/273653/217090673-54218311-2cec-4693-9d80-e1fc08123e4d.png">

It says there is no `main.js` on the Release, but [I do have one on the release](https://github.com/caseywatts/obsidian-compromise/releases/tag/1.0.1).

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/273653/217091651-532af708-5f5b-4e61-9e98-96bf3288df28.png">

I'm not sure what else could be wrong here
- I wonder if something else could be wrong with my main.js file?
- Or is this latest release 1.0.1 not tagged as `latest` in the right way? (it does say `latest`!)
- Could there be some latency (more than minutes, I've waited that long) between updating on github and Obsidian seeing it? Or a caching issue?

I'm happy to help update/clarify the instructions if I missed something :)

**Comment by TfTHacker** [comment]
Hi. The problem is that your manifest.json file in the root folder says version 1.0.0 while your release is 1.0.1. BRAT reads the manifest.json file to get the current version. if you want to use an alternate version, you can use manifest-beta.json (see docs for more info).
