### ISSUE TITLE
Can BRAT detect if plugins are uninstalled and ask before reinstalling them?

### ISSUE THREAD

**Issue by YousufSSyed** [TfTHacker/obsidian42-brat#52]
I've noticed a bunch of times within only a few days of using the plugin, that when I would uninstall plugins installed with BRAT, that BRAT would automatically reinstall them to my inconvenience. What if BRAT kept track of plugins it installed (perhaps in a JSON file?) and if it detects that it is no longer installed, ask the user if they want it reinstalled, or forget it?

**Comment by TfTHacker** [comment]
Yes, BRAT is a side-loader of plugins and helps with testing. So if you want to remove a plugin installed by BRAT, you can remove it in the standard way. But if you want to prevent BRAT from updating it, you also need to remove it from BRAT in settings.

**Comment by YousufSSyed** [comment]
@TfTHacker Would it be possible to add a settings option where if the app gets removed the standard way, then BRAT can ask / show a notification asking if you want the plugin removed from BRAT? Could it show a section with plugins that were removed the standard way but installed with BRAT with options for either getting the back or keeping it removed?

**Comment by TfTHacker** [comment]
It is possible but goes against the model of a side-loader for testing. It gets complicated to manage too many internals. (Lot of edge cases in testing).

Plus I am lazy and this is just a hobby project, so I don't push for perfection 🤓.

**Comment by YousufSSyed** [comment]
Alright.

**Comment by YousufSSyed** [comment]
@TfTHacker I looked back at this and it is pretty inconvenient to have removed a plugin, and then see BRAT reinstalling it, so I have to do it again and remove it from the list in BRAT.

You've never had to do this?
