### ISSUE TITLE
Is it possible to add support for proxies?

### ISSUE THREAD

**Issue by StrollStars** [TfTHacker/obsidian42-brat#54]
In some areas access to github is not smooth enough, can you add proxy settings?

**Comment by TfTHacker** [comment]
Can you please provide more details?

**Comment by StrollStars** [comment]
@TfTHacker I want BRAT to support proxy, to be able to set the IP address, port, username (optional) and password (optional) of the proxy.
When I update other plugins through BRAT , BRAT accesses through the proxy I set.

**Comment by TfTHacker** [comment]
So after further review, BRAT is using the built in fetch API for Obsidian, which works reliably across devices and platforms. So to get this changed, please submit a suggestion to the Obsidian devs to make it core.
