### ISSUE TITLE
Feature Request: accept .git links when wrtiting / pasting the repo URL for adding plugins

### ISSUE THREAD

**Issue by YousufSSyed** [TfTHacker/obsidian42-brat#55]
Right now it only accepts GitHub URLs for doing so. When I'm cloning repos, my habit is to go to the green code button and copy the `.git` URL. I'd like to be able to paste the repo `.git` URL into BRAT to add the pluign.

**Comment by TfTHacker** [comment]
This will be fixed soon with the 0.7.1 release. Thank you for suggesting this.
