### ISSUE TITLE
Option to favor theme.json than theme-beta.json

### ISSUE THREAD

**Issue by vanbang9710** [TfTHacker/obsidian42-brat#56]
There's currently no way to auto update a community theme so I hope you add this feature.

**Comment by TfTHacker** [comment]
Even if a theme doesn't have a beta, you can add it to BRAT and BRAT will update them. Its a form of auto-updater.

**Comment by vanbang9710** [comment]
But I prefer stable version

**Comment by TfTHacker** [comment]
I see, so you want it to auto-update from the theme.json even if theme-beta.json exists?

**Comment by vanbang9710** [comment]
yes
