### ISSUE TITLE
Doesn't recognise or allow main.ts files

### ISSUE THREAD

**Issue by FackJox** [TfTHacker/obsidian42-brat#57]
Specifically trying to add this repo:
https://github.com/nicucalcea/obsidian-tasks-todo-txt

It gives an error about main.js being missing from the release.

The repo uses main.ts instead.

**Comment by TfTHacker** [comment]
Thank you for reporting this. It seems the developer needs to fix his release for it to work. 

I reached out to them here: https://github.com/nicucalcea/obsidian-tasks-todo-txt/issues/1#issuecomment-1537178589
