### ISSUE TITLE
Follow symlinks for manifest.json

### ISSUE THREAD

**Issue by waynevanson** [TfTHacker/obsidian42-brat#59]
Currently when the manifest.json is at the root is a symlink to another file (packages/<package-name>/manifest.json), the plugin returns a notification saying the repository does not a valid manifest.

This is because the symlink is a file that contains the relative path to the actual file.

**Comment by TfTHacker** [comment]
I've never tried this. Do you know if a symlink is used that works with Obsidian? In other words, does Obsidian follow a sym link?

**Comment by waynevanson** [comment]
After publishing the plugin to obsidian, it looks like they don't use it there either.
