### ISSUE TITLE
one time manual install

### ISSUE THREAD

**Issue by TfTHacker** [TfTHacker/obsidian42-brat#6]
From @gitmurf

t seems like there is a use case for users to use BRAT even if the dev isn’t building the repo properly to use BRAT. Also potentially if you want to manually install an old release. The proposal is that instead of putting repo address like GitMurf/plugin-a/ you could instead put the full release URL in and then BRAT would install that specific release. Maybe it is an added command that you run “ad hoc” and it does t save that repo in a list for future updates or anything.

Basically it is a “one time manual install” command and you just point it to the exact release URL and BRAT simply downloads the release files to install that version.
Does that make sense?

Then you can market BRAT as not only for beta testers but also as the new go to method for installing any plugins manually that doesn’t require the plugin dev to even know what BRAT is. This could be great for older plugins that maybe have been abandoned but people still use them… I know there is a few of them out there.

Would be much easier to explain to someone how to manually install a plugin 🙂 1. Install BRAT 2. Run “one time manual install” command 3. Enter the release URL 4. Make sure the plugin is now available and enabled.

**Comment by Taitava** [comment]
Sounds reasonable. It could help to install and try out new plugins too, that are not yet available in the community plugins list.

For me as a developer, it would be really nice to be able to provide users with instructions on how to downgrade my plugin, in case some update causes problems for them. But then they'd have do deal with the pain of migrating their data.json config file back to a format supported by the older plugin version - but that's another story.

**Comment by TfTHacker** [comment]
Yes I will likely implement this, it does make sense based on the scenarios presented.

**Comment by TfTHacker** [comment]
After review, this is beyond the scope of general user scenarios,  sorry. Pull requests are always welcome :-)
