### ISSUE TITLE
Force update plugins

### ISSUE THREAD

**Issue by polyipseity** [TfTHacker/obsidian42-brat#62]
Currently BRAT only updates a plugin if the manifest version has changed. Is it possible to add a command that updates a plugin unconditionally? It would be helpful for me as my plugins have a latest release that does not change the manifest version but the content of the JS file.

**Comment by TfTHacker** [comment]
Great idea. Will keep in mind for next update.

**Comment by TfTHacker** [comment]
I am working on the feature and wonder if it should be called: "Reinstall beta plugin" - because we are not really updating but rather grabbing the plugin and redownloading the files. It could even be "redownload beta plugin".

Any thoughts on how to name the command?

**Comment by TfTHacker** [comment]
This will be available in the 1.7.1 update, which should be pushed out soon. I went with "Reinstall" plugin. Let me know if you think it should be named something different.

**Comment by polyipseity** [comment]
> I am working on the feature and wonder if it should be called: "Reinstall beta plugin" - because we are not really updating but rather grabbing the plugin and redownloading the files. It could even be "redownload beta plugin".
> 
> Any thoughts on how to name the command?

"Reinstall" does sound better.
