### ISSUE TITLE
Support private repo release

### ISSUE THREAD

**Issue by HananoshikaYomaru** [TfTHacker/obsidian42-brat#64]

**Comment by TfTHacker** [comment]
This is beyond the scope of what I plan to implement with BRAT. PR's welcome :-)

Unless there is an easy way to do it without authentication (which I don't want to build into BRAT).

**Comment by HananoshikaYomaru** [comment]
I think you don't need to build the whole github authentication into BRAT, all you need is just a personal access token. 

<img width="283" alt="CleanShot 2023-11-14 at 07 58 44@2x" src="https://github.com/TfTHacker/obsidian42-brat/assets/43137033/b6582224-5cac-42f6-8adc-70e701465aa7">

if you want to do it, I guess you reopen this issue and I want to see if I have time to do it someday.
