### ISSUE TITLE
Problem installing old plugin version.

### ISSUE THREAD

**Issue by TheEmanuelSampaio** [TfTHacker/obsidian42-brat#65]
First of all, i'm new on git, so sorry if i'm saing something stupity. I was tring istall one version (or commit) of a plugin (this: https://github.com/brosell/obsidian-auto-note-organizer/tree/fdd77144d3aed6a6f23ad50ffd4d347987f0cfee), but aparently the /tree/code link doesnt work. It says that the manifest.json doesn't exist, but it does! Why it doesn't work? 
Thank's in advance!

![Captura de tela 2023-11-06 122536](https://github.com/TfTHacker/obsidian42-brat/assets/150048301/4003e201-444d-43e8-a236-3d2b3579652f)

**Comment by TfTHacker** [comment]
Try the "Add a beta plugin with frozen version based on release tag."

It will pull old releases. Though it doesn't update after that. Also it doesn't pull from specific branches in the tree, rather previous releases of a plugin.

I hope that helps.
