### ISSUE TITLE
[BUG] BRAT `0.8.0` fails to install beta plugin, where as `0.7.2` works without issue

### ISSUE THREAD

**Issue by mProjectsCode** [TfTHacker/obsidian42-brat#71]
After upgrading to BRAT `0.8.0` I noticed that it now fails to install the latest [Meta Bind Beta release](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/releases/tag/0.9.0-canary.20231210T004630). 

The error message and console output seem to indicate that BRAT can not find the `main.js` file, which is strange, since it is included in the release and BRAT `0.7.2` installed this release without issue.

Console output:
![image](https://github.com/TfTHacker/obsidian42-brat/assets/61602848/3b09fd29-20fc-4c07-a0a7-3a03cbb0cd74)

**Comment by TfTHacker** [comment]
This should be resolved with 0.8.1.
