### ISSUE TITLE
[Feature] An option to auto-enable plugin after installation

### ISSUE THREAD

**Issue by RyotaUshio** [TfTHacker/obsidian42-brat#72]
Sometimes, I find it a little bit tedious to manually enable a beta plugin that I installed via BRAT.
Since most users will only install plugins that they really want to try, I think it would be nice to have the option to automatically enable installed plugins. 

What do you think? If you are positive, I can implement it myself and send a PR when I have time.

**Comment by RyotaUshio** [comment]
I think there are two options:

1. Add an "Add & Enable Plugin" button next to the "Add Plugin" button in the modal
2. Add an "Auto-enable plugins after installation" toggle setting next to the "Auto-update plugins at startup" setting

**Comment by TfTHacker** [comment]
I agree with this recommendation. I have been thinking about this for a while myself. If you want to do a PR that would be great.

**Comment by RyotaUshio** [comment]
Great! So which option do you think is better?

> I think there are two options:
> 
> 1. Add an "Add & Enable Plugin" button next to the "Add Plugin" button in the modal
> 2. Add an "Auto-enable plugins after installation" toggle setting next to the "Auto-update plugins at startup" setting

The first one will give us more fine-grained control but potentially clutter the modal UI.

**Comment by TfTHacker** [comment]
I was kind of thinking both options have value.

1) What about having a toggle in settings to set a "global" default for "auto enable"

2) when using the add plugin form, next to the input field for the URL for the github repo, add a checkbox "Enable after installing the plugin." So this value can be toggled on and off. It would base its "default" value to the global setting.

I also think setting it to true, that is setting it to enabled should become the default.

When I first developed this, I was worried people would be concerned about security, so it made them go an extra step to activate the plugin. But I don't think now this is really a concern of people.

**Comment by RyotaUshio** [comment]
Your idea sounds perfect. I will implement it when I can find time!
