### ISSUE TITLE
files "missing" from repo but they really aren't

### ISSUE THREAD

**Issue by huachuman** [TfTHacker/obsidian42-brat#75]
Lately I've been getting the message a lot that a given plugin or theme has no manifest.json, main.js, or theme.css or whathaveyou, but the repo clearly has those in the root directory, and they are properly named. I even just got that notification for one of the beta plugins I had already successfully installed after BRAT tried to update the plugin.

I've encountered this error probably 6 times just today.

**Comment by huachuman** [comment]
e.g. https://github.com/yan42685/obsidian-clever-search

**Comment by TfTHacker** [comment]
Hi there,

The problem with the example repo is that while it does have manifest in the root, it doesn't have a release in the repo corresponding to the release version in manifest.json. 

BRAT first reads manifest.json to get the release version, then downloads that release.

This is a mistake many devs make when starting Obsidian development. Obsidian also can't download the plugin unless there is a corresponding release.

This is one of the values of BRAT; in effect, BRAT is showing the repo is not configured correctly.

Warm regards.

**Comment by huachuman** [comment]
Is this not related to https://github.com/TfTHacker/obsidian42-brat/issues/71 ?

Despite your explanation I do find it strange that I have only started to encounter this error recently. Am I imagining things? Or could an update to BRAT have broken something?

**Comment by TfTHacker** [comment]
It is absolutely possible an update broke something 😃. 

However, in the case of the repo you gave as an example, the manifest.json has a release identifier, but there is no published release with that identifier, so nothing can be downloaded. It might be that you succeeded earlier with a previous release before the developer made a change to the manifest.json in the meantime. It is common for developers to make a change to manifest.json even though they haven't published a release. But this will also break Obsidian's ability to download the plugin.

Can you provide me with some other repo's for me to examine?
