### ISSUE TITLE
Toggle plugins on/off from BRAT

### ISSUE THREAD

**Issue by menagerie198** [TfTHacker/obsidian42-brat#8]
It would be proper cool to be able to toggle a plugin on/off with BRAT.  Basically a command to enable or disable a plugin via the / or Command Palette? Thus BRAT becomes something like a 'Plugin Manager'; similar to 'Configure Snippets'? A statusbar modal would be lovely.

**Comment by menagerie198** [comment]
I might be using the wrong terminology. @Chetachi's 'MySnippets' (sorry, I called it by the wrong name above) plugin puts an icon in the status bar. Clicking on that throws up a window with all my snippets listed, with a wall of toggles, and command to open the snippet in an editor. If we could similarly toggle plugins on/off, and open 'plugin options' that would be great.

**Comment by TfTHacker** [comment]
This will be pushed out to community plugins channel here shortly with version 0.5.0

However it is available with the enable or disable command palette commands. I like your idea of a popup list, but this was a lot more work :-)

lets give this solution a try to see if it is sufficient. But i can say I already love this feature.
