### ISSUE TITLE
[New Feature]Can you add the feature for go back to the old version

### ISSUE THREAD

**Issue by Skywind5487** [TfTHacker/obsidian42-brat#80]
When I update the plugins, some of them just do not work on my device.
I want to find a way to go back to the old version, but there is no way.
I noticed that Brat has a feature that can update to the specific version, I hope there is a feature can let me go back to the old version.

Btw, I'm using an iPhone, so I’m at my wits’ end with this problem.

**Comment by TfTHacker** [comment]
There is a feature where you can use an old version of a plugin. Here is the instructions:

https://tfthacker.com/brat-plugins#Frozen+version+based+on+a+release+tag

**Comment by Skywind5487** [comment]
Thank you very much!!!
