### ISSUE TITLE
[FR] Collab with Obsidian VARE?

### ISSUE THREAD

**Issue by anonhostpi** [TfTHacker/obsidian42-brat#83]
It seems like these 2 plugins target similar functionality and are maintained at a similar frequency.

If that's the case, I'd like to suggest that you combine your efforts and move both into a gh org.

You are both MIT licensed, so it seems like you are both are on the same page about IP.

**Comment by anonhostpi** [comment]
relevant: https://github.com/4Source/vare-obsidian-plugin/issues/10

**Comment by 4Source** [comment]
There are indeed pretty similar my plugin is inspired by BRAT. My goal was to provide a more user friendly interface

**Comment by anonhostpi** [comment]
I do like VARE's interface. The ability to pull from existing plugins is nice.

I also like BRAT's options like these:

![image](https://github.com/TfTHacker/obsidian42-brat/assets/130698314/66f5bbe0-3fed-47f1-af3f-5920c21559d9)
![image](https://github.com/TfTHacker/obsidian42-brat/assets/130698314/36b446f7-18c8-40fa-917a-ee948d28d130)

**Comment by 4Source** [comment]
If @TfTHacker is interested in a combined plugin I think we could do this
