### ISSUE TITLE
Pass URI argument for “enable plugin” 

### ISSUE THREAD

**Issue by csss1234** [TfTHacker/obsidian42-brat#84]
Trying to make a clickable link to enable a plugin. I use advanced URI to make this link
`obsidian://advanced-uri?vault=Vault&commandid=obsidian42-brat%253ABRAT-enablePlugin`
But then it pulls up a modal for selecting. Would be great if I could append something like “&plugin=dataview” so that i can enable a plugin with one tap

**Comment by TfTHacker** [comment]
So after a little research, this is possible using the Advanced URI plugin, which is documented [here](https://publish.obsidian.md/advanced-uri-doc/Actions/Miscellaneous) with the `enable-plugin` and `disable-plugin` commands.

To disable a plugin, use the command like this:

`[Disable](obsidian://advanced-uri?disable-plugin=obsidian42-brat)`

To enable a plugin you would do this:

`[Enable](obsidian://advanced-uri?enable-plugin=obsidian42-brat)`

However, this did not work for me for some plugins, so an alternative is to turn on "Allow executing arbitrary code via eval" and then using:

`[Enable](obsidian://advanced-uri?eval=this.app.plugins.enablePluginAndSave("obsidian42-brat"))`
