### ISSUE TITLE
Unable to add Google drive sync plugin to iPhone due to missing file?

### ISSUE THREAD

**Issue by Ksan6861** [TfTHacker/obsidian42-brat#91]
![IMG_8477](https://github.com/user-attachments/assets/9baa639f-0703-49e7-9d30-faaa22593382)
![IMG_8478](https://github.com/user-attachments/assets/c5179d43-7640-4194-8194-7dd55a2982de)

hi - NON-coder here trying to add the Google drive sync plugin to my iPhone so I can stop spending $5/month to sync across devices. 

I’m getting an error when trying to upload the sync plugin through BRAT, but the plugin works fine on my desktop. Checking in with you to see if this error is something on the BRAT side or if I need to ask the Google sync plugin owner for the file type specified in the error…?

BRAT is looking for a main.js file and the sync plugin has a main.ts file? 

Thanks for any help you can provide on this.

**Comment by TfTHacker** [comment]
I just tested and this is working. Likely the developer fixed the release.
